# Generated by Django 4.0 on 2021-12-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_edit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
