# Generated by Django 4.0 on 2021-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_left_note_top_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='left',
            field=models.CharField(default='45vw', max_length=7),
        ),
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.CharField(default='45vh', max_length=7),
        ),
    ]
