# Generated by Django 4.0 on 2021-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_left_alter_note_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='left',
            field=models.CharField(default='35vw', max_length=7),
        ),
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.CharField(default='35h', max_length=7),
        ),
    ]
