# Generated by Django 4.0 on 2021-12-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_left_alter_note_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.CharField(default='37h', max_length=7),
        ),
    ]
